# Generated by Django 5.0.6 on 2024-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=128)),
                ("number", models.CharField(max_length=3)),
                ("code", models.CharField(max_length=3)),
                ("given_name", models.CharField(max_length=64)),
                ("surname", models.CharField(max_length=64)),
                ("dob", models.DateField()),
                ("nationality", models.CharField(max_length=64)),
                ("wiki_url", models.URLField()),
            ],
        ),
    ]
